### ISSUE TITLE
API Reference: the base url in the "example" request should be app.premai.io

### ISSUE THREAD

**Issue by tiero** [premAI-io/prem-saas-docs#3]
If is possible, we should use the right base url of the production environment, not `http://premai.io`

## Current 

```bash
curl --request POST \
  --url https://premai.io/v1/chat/completions \
  --header 'Authorization: <api-key>' \
  --header 'Content-Type: application/json'
```

**Comment by nsosio** [comment]
Fixed 
![Screenshot 2024-04-13 at 12 27 02](https://github.com/premAI-io/prem-saas-docs/assets/5698130/8c401652-1636-467f-b361-19617eb8a260)
