### ISSUE TITLE
Update Models

### ISSUE THREAD

**Issue by nsosio** [premAI-io/prem-saas-docs#35]
Update supported models to reflect

|alias|tier|
|-----|----|
|claude-3-opus|high|
|gpt-4-eu|high|
|command-r-plus|medium|
|claude-3.5-sonnet|medium|
|gpt-4o|medium|
|mistral-large|medium|
|claude-3-sonnet|medium|
|gpt-4-turbo|medium|
|gemini-pro|medium|
|claude-3-haiku|low|
|command-r|low|
|mixtral-8x7b-fast|low|
|gemma-7b-it-fast|low|
|llama-3-8b-instruct|low|
|remm-slerp-l2-13b|low|
|yi-34-chat|low|
|zephyr-7b-beta|low|
|mythomax-l2-13b|low|
|chronos-hermes-13b|low|
|mixtral-8x22b|low|
|codellama-70b-instruct|low|
|mistral-7b-instruct-v0.1|low|
|mixtral-8x7b-instruct-v0.1|low|
|dolphin-mixtral-8x7b|low|
|mythalion-13b|low|
|rwkv-5-world-3b|low|
|llama-3-70b-instruct|low|
|gpt-3.5-turbo-eu|low|
|stripedhyena-nous-7b|low|
|gemma-7b-it|low|
|mistral-small|low|
|llama-3-70b-fast|low|
|llama-3-8b-fast|low|
|gpt-3.5-turbo|low|

**Comment by Anindyadeep** [comment]
Closing this issue :)

cc: @nsosio
